# Generated by Django 5.0.3 on 2024-03-26 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StorageAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organizationUid', models.CharField(default='3110a9da-7ea1-4857-98cb-c3e5c46b6dd6', max_length=255)),
                ('role', models.CharField(default='CompanyTenant', max_length=255)),
                ('mfaPolicyStatus', models.CharField(default='Disabled', max_length=255)),
                ('firstName', models.CharField(max_length=100)),
                ('lastName', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('phone', models.CharField(max_length=20)),
                ('userName', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('siteUid', models.CharField(default='b65acaf4-e282-4096-9e56-8c840442a3a3', max_length=100)),
                ('companySiteBackupResourceUid', models.CharField(default='a2b21ca5-55cc-4616-8b39-6270c0741b26', max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('vcdUserId', models.CharField(blank=True, max_length=100, null=True)),
                ('resourceFriendlyName', models.CharField(max_length=100)),
                ('storageQuota', models.BigIntegerField()),
                ('isStorageQuotaUnlimited', models.BooleanField(default=False)),
            ],
        ),
    ]
