# Generated by Django 5.0.3 on 2024-03-26 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backup_portal', '0004_alter_storageallocation_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storageallocation',
            name='address',
            field=models.CharField(default='null', max_length=255),
        ),
        migrations.AlterField(
            model_name='storageallocation',
            name='description',
            field=models.TextField(default='null'),
        ),
        migrations.AlterField(
            model_name='storageallocation',
            name='vcdUserId',
            field=models.CharField(default='null', max_length=100),
        ),
    ]
