# Generated by Django 5.0.3 on 2024-03-26 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VSPCUser',
        ),
    ]
